### ISSUE TITLE
Bot posts approved builds multiple times (2)

### ISSUE THREAD

**Issue by Kroohpyyh** [deathbeam/poe-builds-discord-bot#16] opened 2020-10-21 16:51 UTC
When approving a build, it gets posts multiple times (usually 2) on the approved builds channel.

Parsing from google sheet api works fine to approval channel.

**Comment by deathbeam** [comment] 2020-10-23 22:20
This is probably same issue as #14, probs needs some more investigation so closing.

Duplicate of #14

**Closed as completed by deathbeam** 2020-10-23 22:20 UTC
Labels: bug, duplicate
